### ISSUE TITLE
XMLHttpRequest error.

### ISSUE THREAD

**Issue by jeansebastienZ** [gabrielpacheco23/google-translator#39]
```
Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 909:28                get current
packages/http/src/browser_client.dart 71:22                                       <fn>
dart-sdk/lib/async/zone.dart 1687:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 155:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 707:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 736:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 533:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37324:58                              <fn>


    at Object.createErrorWithStack (http://localhost:59913/dart_sdk.js:5372:12)
    at Object._rethrow (http://localhost:59913/dart_sdk.js:39565:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59913/dart_sdk.js:39559:13)
    at Object._microtaskLoop (http://localhost:59913/dart_sdk.js:39386:13)
    at _startMicrotaskLoop (http://localhost:59913/dart_sdk.js:39392:13)
    at http://localhost:59913/dart_sdk.js:34875:9
```

**Comment by jeansebastienZ** [comment]
Everything was working fine, but suddenly it

**Comment by zensarCompass** [comment]
I am using flutter web and facing some issue. Any resolution for same?
